version: 3
services:
  fpm:
    build: .
    volumes:
      - ./:/var/www/html
    restart: always

  nginx:
    image: nginx:1.17.4-alpine
    volumes:
      - ./:/var/www/html
      - ./deploy/nginx/dev/default.conf:/etc/nginx/conf.d/default.conf