version: '3'
services:
  fpm:
    build: .
    volumes:
      - ./:/var/www/html
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: always
    depends_on:
      - mysql
      - redis
    dns:
      - 178.22.122.100
      - 185.51.200.2

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./:/var/www/html
      - ./deploy/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 8989:80
    depends_on:
      - fpm

  mysql:
    image: mysql:8.0.17
    restart: always
    volumes:
      - nitmddb:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 3360:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'root'

  redis:
    image: redis:alpine
    restart: always


volumes:
  nitmddb: